import { Media } from '@/payload-types'
import { RequiredDataFromCollectionSlug } from 'payload'

type WorkArgs = {
  image: Media
}

// 12 titles generated by AI
const titles = [
  'The Power of Visual Storytelling in the Digital Age',
  'Designing for Impact: How Purpose-Driven Brands are Shaping the Future',
  'Beyond Aesthetics: The Role of Design in Building Brand Loyalty',
  'Crafting Experiences: The Intersection of Design and User Engagement',
  'The Evolution of Branding: Embracing Change in a Dynamic Market',
  'Designing for Diversity: How Inclusive Design is Transforming Brands',
  'The Art of Simplicity: Minimalist Design in a Complex World',
  'Sustainability in Design: How Eco-Friendly Practices are Reshaping Brands',
  'The Psychology of Color: How Brands Use Color to Influence Consumer Behavior',
  'Designing for Emotion: The Role of Storytelling in Brand Identity',
  'The Future of Branding: How Technology is Revolutionizing Design',
  'Designing for Social Impact: How Brands are Driving Change through Design',
]

// 12 descriptions generated by AI
const descriptions = [
  "In an era dominated by fleeting attention spans and information overload, visual storytelling has emerged as a powerful tool for brands to connect with their audiences on a deeper level. By leveraging compelling imagery, videos, and design, brands can transcend traditional marketing and create immersive experiences that resonate emotionally with consumers.",
  "Purpose-driven brands are reshaping the business landscape by prioritizing social and environmental impact alongside profit. Through thoughtful design, these brands communicate their values and mission, fostering deeper connections with consumers who share their commitment to making a positive difference in the world.",
  "Design is no longer just about aesthetics; it's a critical component of building brand loyalty. By creating meaningful and memorable experiences through design, brands can forge emotional connections with their customers, fostering trust and loyalty that goes beyond the product or service itself.",
  "The intersection of design and user engagement is where magic happens. By crafting experiences that are not only visually appealing but also intuitive and user-friendly, brands can captivate their audiences and create lasting impressions that drive engagement and loyalty.",
  "Branding is an ever-evolving field, and successful brands are those that embrace change and adapt to the dynamic market. By staying attuned to cultural shifts, consumer preferences, and technological advancements, brands can remain relevant and continue to resonate with their audiences.",
  "Inclusive design is transforming the way brands approach their products and services. By designing for diversity, brands can create more accessible and welcoming experiences that cater to a broader range of consumers, fostering inclusivity and driving positive social change.",
  "In a world filled with complexity, simplicity can be a powerful design principle. Minimalist design focuses on stripping away the unnecessary to create clean, elegant, and impactful experiences that resonate with consumers seeking clarity and authenticity.",
  "Sustainability is becoming a key consideration in design as brands recognize the importance of eco-friendly practices. By incorporating sustainable materials, processes, and messaging into their design strategies, brands can appeal to environmentally conscious consumers and contribute to a more sustainable future.",
  "Color plays a crucial role in branding, influencing consumer behavior and perceptions. By understanding the psychology of color, brands can strategically use color to evoke emotions, convey messages, and create a strong visual identity that resonates with their target audience.",
  "Storytelling is a powerful tool in brand identity, allowing brands to connect with their audiences on an emotional level. By designing for emotion, brands can create compelling narratives that resonate with consumers and foster deeper connections that go beyond the functional aspects of their products or services.",
  "The future of branding is being shaped by technology, revolutionizing the way brands design and interact with their audiences. From augmented reality to artificial intelligence, technology is opening up new possibilities for creative expression and engagement, allowing brands to push the boundaries of traditional design.",
  "Designing for social impact is becoming increasingly important as brands recognize their role in driving positive change. By incorporating social impact into their design strategies, brands can create meaningful experiences that not only resonate with consumers but also contribute to a better world.",
]

export const generateWork: (args: WorkArgs) => RequiredDataFromCollectionSlug<'works'> = ({
  image,
}) => {
  const title = titles[Math.floor(Math.random() * titles.length)]
  const description = descriptions[Math.floor(Math.random() * descriptions.length)]
  
  return {
    // random title
    title,
    slug: title.toLowerCase().replace(/ /g, '-').replace(/[^\w-]+/g, ''),
    _status: 'published',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: description,
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    image: image.id,
    meta: {
      description: `Money isn't just currency; it's a language. Dive deep into its nuances, where strategy meets intuition in the vast sea of finance.`,
      image: image.id,
      title: 'Dollar and Sense: The Financial Forecast',
    },
  }
}
